service: campaigns
useDotenv: true
custom:
  serverless-offline:
    noPrependStageInUrl: true
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    DB_SECRET: ${env:DB_SECRET}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    GPT_KEY: ${env:GPT_KEY}

functions:
  get-candidate:
    handler: src/get-candidate/handler.handler
    name: get-candidate
    events:
      - http:
          path: get-candidate
          method: get
  get-candidate-template:
    handler: src/get-candidate-template/handler.handler
    name: get-candidate-template
    events:
      - http:
          path: get-candidate-template
          method: post
plugins:
  - serverless-webpack
  - serverless-offline
